[package]
name = "xbee_rust_modem_library"
version = "0.1.0"
edition = "2024"

[dependencies]
serialport = "4.8.1"
heapless = { version = "0.8", features = ["serde"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
postcard = "1.1"
